stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:14-alpine
  script:
    - yarn install
    - yarn build

test:
  stage: test
  image: node:14-alpine
  script:
    - yarn test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: registry.gitlab.com/<Elias Ortega>/<ProyectoFinalTendencias>:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME